### ISSUE TITLE
SUIVP-1 Warning by Xcode on newly generated project

### ISSUE THREAD

**Issue by exgael** [maukur/SwiftUI-Viper-Architecture#1]
Hello,

I noticed that when using the template for a new projet, I get a warning by Xcode.

File: ApplicationViewBuilder
lines :
```swift
@MainActor
final class ApplicationViewBuilder : Assembly, ObservableObject {
```

Warning:

**Comment by maukur** [comment]
I just removed the @MainActor attribute, cause ApplicationViewBuilder is a special class that should be called in the RootApp initialization. The initializator is always run in the main thread. 

The new architecture version is available as 1.0.1   

@exgael thanks!
